kind: pipeline
name: build

steps:
  - name: fetch
  image: alpine/git
  commands:
    - git fetch http://yasinshaw.com:10081/xiaoyao/concurrent +refs/heads/develop

  - name: docker
    image: plugins/docker
    settings:
      username: yasinshaw
      password:
        from_secret: docker_password
      repo: registry.cn-hangzhou.aliyuncs.com/yasinshaw/concurrent
      registry: registry.cn-hangzhou.aliyuncs.com
      mirror: https://mzayqkhl.mirror.aliyuncs.com
      tags: latest

---
kind: pipeline
type: ssh
name: deploy

server:
  host: yasinshaw.com
  user: root
  ssh_key:
    from_secret: ssh_key

steps:
  - name: pull image
    environment:
      DOCKER_PASSWORD:
        from_secret: docker_password
    commands:
      - docker login --username=yasinshaw --password=$DOCKER_PASSWORD registry.cn-hangzhou.aliyuncs.com
      - docker pull registry.cn-hangzhou.aliyuncs.com/yasinshaw/concurrent:latest

  - name: remove old container
    failure: ignore
    commands:
      - docker rm -f -v concurrent 

  - name: start container
    commands:
      - docker run -d --name=concurrent --restart=always -p 4000:4000 registry.cn-hangzhou.aliyuncs.com/yasinshaw/concurrent:latest
depends_on:
  - build
